# Generated by Django 2.0.6 on 2019-06-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.SmallIntegerField()),
                ('age', models.SmallIntegerField()),
                ('operation', models.CharField(max_length=20)),
            ],
        ),
    ]
